"""Synthetic Seed Data Generator for Corporate Banking Change of Account Mandate.

Populates PostgreSQL (`corporate_mandate_db`) with:
- 5 distinct corporate customer profiles (`CUST-001` .. `CUST-005`)
- 17 bank accounts across SGD, USD, EUR, CNH, JPY
- 23 signatories across Groups A, B, and C
- 13 tiered signing rules
- 5 board resolutions (BRC-09, custom board minutes, LLP partners resolution)
- 5 Change of Mandate applications (`COM-2026-...`)
- 18 immutable audit log entries
- 1 active workspace state (`DEFAULT_WORKSPACE` -> `CUST-001`)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.db import get_connection


CUSTOMERS_SEED: list[dict[str, Any]] = [
    {
        "customer_id": "CUST-001",
        "company_name": "TechNova Solutions Pte Ltd",
        "uen": "201823901E",
        "entity_type": "TECH_STARTUP",
        "industry": "AI & Enterprise Cloud SaaS",
        "incorporation_country": "SG",
        "kyc_status": "VERIFIED",
        "ideal_corp_id": "IDEALSG-TN2018",
        "ideal_auth_status": "IDEAL_TOKEN_AUTHENTICATED",
        "active_mandate_version": 3,
        "mandate_status": "ACTIVE",
        "relationship_manager": "Vivian Tan (VP, TMT Corporate Banking)",
        "registered_address": "71 Ayer Rajah Crescent, #04-12, LaunchPad @ one-north, Singapore 139951",
        "governance_policy": {
            "min_group_a_signatories": 1,
            "recommended_group_a_signatories": 2,
            "requires_brc09_for_mandate_change": True,
            "dual_control_maker_checker": True,
            "aliases": ["TechNova", "TechNova Solutions"],
        },
    },
    {
        "customer_id": "CUST-002",
        "company_name": "Meridian Pacific Logistics Pte Ltd",
        "uen": "199804512K",
        "entity_type": "SME",
        "industry": "Regional Maritime & Precision Cold-Chain Logistics",
        "incorporation_country": "SG",
        "kyc_status": "VERIFIED",
        "ideal_corp_id": "IDEALSG-MP1998",
        "ideal_auth_status": "IDEAL_TOKEN_AUTHENTICATED",
        "active_mandate_version": 2,
        "mandate_status": "AMENDMENT_IN_PROGRESS",
        "relationship_manager": "Kelvin Chua (SVP, Commercial Banking SME)",
        "registered_address": "18 Tuas South Avenue 5, #02-01, Meridian Logistics Hub, Singapore 637310",
        "governance_policy": {
            "min_group_a_signatories": 1,
            "recommended_group_a_signatories": 2,
            "requires_brc09_for_mandate_change": True,
            "dual_control_maker_checker": True,
            "aliases": ["Meridian Pacific", "Merlion Precision Engineering Pte Ltd", "Merlion Precision"],
        },
    },
    {
        "customer_id": "CUST-003",
        "company_name": "Apex Global Holdings (SG) Pte Ltd",
        "uen": "201239884M",
        "entity_type": "MNC_SUBSIDIARY",
        "industry": "Regional APAC Treasury & Supply Chain Center",
        "incorporation_country": "SG",
        "kyc_status": "VERIFIED_ENHANCED_CDD",
        "ideal_corp_id": "IDEALSG-AG2012",
        "ideal_auth_status": "IDEAL_HOST_TO_HOST_AND_TOKEN",
        "active_mandate_version": 5,
        "mandate_status": "ACTIVE",
        "relationship_manager": "Ananya Deshmukh (MD, Global Institutional Banking)",
        "registered_address": "12 Marina Boulevard, #35-02, Marina Bay Financial Centre Tower 3, Singapore 018982",
        "governance_policy": {
            "min_group_a_signatories": 1,
            "recommended_group_a_signatories": 2,
            "requires_brc09_for_mandate_change": True,
            "dual_control_maker_checker": True,
            "aliases": ["Apex Global", "Pacific Rim Logistics (APAC) Holdings Pte. Ltd.", "Pacific Rim Logistics"],
        },
    },
    {
        "customer_id": "CUST-004",
        "company_name": "Veritas Legal & Advisory LLP",
        "uen": "T15LL0892F",
        "entity_type": "PARTNERSHIP_LLP",
        "industry": "Corporate M&A Law, Conveyancing & Escrow Practice",
        "incorporation_country": "SG",
        "kyc_status": "VERIFIED_LAW_SOCIETY_REGULATED",
        "ideal_corp_id": "IDEALSG-VL2015",
        "ideal_auth_status": "IDEAL_TOKEN_AUTHENTICATED",
        "active_mandate_version": 4,
        "mandate_status": "ACTIVE",
        "relationship_manager": "Claire Lim (Director, Professional Services Banking)",
        "registered_address": "1 Raffles Place, #44-01, One Raffles Place Tower 1, Singapore 048616",
        "governance_policy": {
            "min_group_a_signatories": 1,
            "recommended_group_a_signatories": 2,
            "requires_brc09_for_mandate_change": True,
            "law_society_client_escrow_dual_partner": True,
            "aliases": ["Veritas Legal", "Stamford & Raffles Legal Chambers LLP", "Stamford & Raffles"],
        },
    },
    {
        "customer_id": "CUST-005",
        "company_name": "Banyan Artisans & F&B Group Pte Ltd",
        "uen": "200511890W",
        "entity_type": "REGULATED_IMPORT_EXPORT",
        "industry": "Specialty Agri-Food Import/Export & Hospitality",
        "incorporation_country": "SG",
        "kyc_status": "VERIFIED_SFA_AND_CUSTOMS",
        "ideal_corp_id": "IDEALSG-BA2005",
        "ideal_auth_status": "IDEAL_TOKEN_AUTHENTICATED",
        "active_mandate_version": 2,
        "mandate_status": "ACTIVE",
        "relationship_manager": "Jonathan Seah (VP, Trade & Commodity Finance)",
        "registered_address": "80 Pasir Panjang Road, #15-82, Mapletree Business City, Singapore 117372",
        "governance_policy": {
            "min_group_a_signatories": 1,
            "recommended_group_a_signatories": 2,
            "requires_brc09_for_mandate_change": True,
            "dual_control_maker_checker": True,
            "aliases": ["Banyan Artisans", "Golden Archipelago Agri-Commodities Pte Ltd", "Golden Archipelago"],
        },
    },
]


ACCOUNTS_SEED: list[dict[str, Any]] = [
    # CUST-001 (3 accounts)
    {
        "account_id": "ACC-001-01",
        "customer_id": "CUST-001",
        "account_number": "001-928341-0",
        "account_name": "DBS Corporate Operating Account (SGD)",
        "account_type": "OPERATING",
        "currency": "SGD",
        "current_balance": 1450820.50,
        "available_balance": 1435820.50,
        "sgd_equivalent_balance": 1450820.50,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "STANDARD_CORPORATE_MANDATE",
    },
    {
        "account_id": "ACC-001-02",
        "customer_id": "CUST-001",
        "account_number": "001-928341-8",
        "account_name": "DBS Multi-Currency SaaS Collections (USD)",
        "account_type": "MULTI_CURRENCY",
        "currency": "USD",
        "current_balance": 885400.00,
        "available_balance": 885400.00,
        "sgd_equivalent_balance": 1195290.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "STANDARD_CORPORATE_MANDATE",
    },
    {
        "account_id": "ACC-001-03",
        "customer_id": "CUST-001",
        "account_number": "001-928349-2",
        "account_name": "IMDA & EDB R&D Grant Escrow Account (SGD)",
        "account_type": "ESCROW_TRUST",
        "currency": "SGD",
        "current_balance": 500000.00,
        "available_balance": 500000.00,
        "sgd_equivalent_balance": 500000.00,
        "is_included_in_mandate_change": False,
        "mandate_scope_tag": "RINGFENCED_GRANT_ESCROW",
    },
    # CUST-002 (3 accounts)
    {
        "account_id": "ACC-002-01",
        "customer_id": "CUST-002",
        "account_number": "003-441092-1",
        "account_name": "SGD Corporate Fleet & Port Settlement",
        "account_type": "OPERATING",
        "currency": "SGD",
        "current_balance": 628910.00,
        "available_balance": 615000.00,
        "sgd_equivalent_balance": 628910.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "STANDARD_CORPORATE_MANDATE",
    },
    {
        "account_id": "ACC-002-02",
        "customer_id": "CUST-002",
        "account_number": "003-441092-9",
        "account_name": "USD Maritime Freight Clearing Account",
        "account_type": "MULTI_CURRENCY",
        "currency": "USD",
        "current_balance": 312050.75,
        "available_balance": 312050.75,
        "sgd_equivalent_balance": 421268.51,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "STANDARD_CORPORATE_MANDATE",
    },
    {
        "account_id": "ACC-002-03",
        "customer_id": "CUST-002",
        "account_number": "003-441095-4",
        "account_name": "EUR Cold-Chain Equipment LC Account",
        "account_type": "TRADE_FINANCE_FX",
        "currency": "EUR",
        "current_balance": 195000.00,
        "available_balance": 180000.00,
        "sgd_equivalent_balance": 284700.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "TRADE_LC_MANDATE",
    },
    # CUST-003 (4 accounts)
    {
        "account_id": "ACC-003-01",
        "customer_id": "CUST-003",
        "account_number": "008-772301-0",
        "account_name": "APAC Regional Cash Concentration Sweep (SGD)",
        "account_type": "TREASURY_SWEEP",
        "currency": "SGD",
        "current_balance": 8940120.00,
        "available_balance": 8940120.00,
        "sgd_equivalent_balance": 8940120.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "APAC_TREASURY_POOL",
    },
    {
        "account_id": "ACC-003-02",
        "customer_id": "CUST-003",
        "account_number": "008-772301-8",
        "account_name": "Global Intercompany Liquidity Account (USD)",
        "account_type": "MULTI_CURRENCY",
        "currency": "USD",
        "current_balance": 14250600.00,
        "available_balance": 14100000.00,
        "sgd_equivalent_balance": 19238310.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "APAC_TREASURY_POOL",
    },
    {
        "account_id": "ACC-003-03",
        "customer_id": "CUST-003",
        "account_number": "008-772308-5",
        "account_name": "CNH Greater China Trade Settlement Account",
        "account_type": "TRADE_FINANCE_FX",
        "currency": "CNH",
        "current_balance": 22100000.00,
        "available_balance": 22100000.00,
        "sgd_equivalent_balance": 4132700.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "APAC_TREASURY_POOL",
    },
    {
        "account_id": "ACC-003-04",
        "customer_id": "CUST-003",
        "account_number": "008-772309-3",
        "account_name": "Singapore Customs Banker Guarantee Margin (SGD)",
        "account_type": "ESCROW_TRUST",
        "currency": "SGD",
        "current_balance": 1200000.00,
        "available_balance": 1200000.00,
        "sgd_equivalent_balance": 1200000.00,
        "is_included_in_mandate_change": False,
        "mandate_scope_tag": "STATUTORY_BOND_MARGIN",
    },
    # CUST-004 (3 accounts)
    {
        "account_id": "ACC-004-01",
        "customer_id": "CUST-004",
        "account_number": "012-559102-3",
        "account_name": "LLP Chambers Office Operating Account (SGD)",
        "account_type": "OPERATING",
        "currency": "SGD",
        "current_balance": 1180450.00,
        "available_balance": 1180450.00,
        "sgd_equivalent_balance": 1180450.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "OFFICE_OPERATING_MANDATE",
    },
    {
        "account_id": "ACC-004-02",
        "customer_id": "CUST-004",
        "account_number": "012-559109-0",
        "account_name": "Law Society Conveyancing Client Trust Escrow (SGD)",
        "account_type": "ESCROW_TRUST",
        "currency": "SGD",
        "current_balance": 19450000.00,
        "available_balance": 19450000.00,
        "sgd_equivalent_balance": 19450000.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "LAW_SOCIETY_CLIENT_TRUST",
    },
    {
        "account_id": "ACC-004-03",
        "customer_id": "CUST-004",
        "account_number": "012-559104-8",
        "account_name": "Cross-Border M&A Advisory Retainer Account (USD)",
        "account_type": "MULTI_CURRENCY",
        "currency": "USD",
        "current_balance": 1620000.00,
        "available_balance": 1620000.00,
        "sgd_equivalent_balance": 2187000.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "OFFICE_OPERATING_MANDATE",
    },
    # CUST-005 (4 accounts)
    {
        "account_id": "ACC-005-01",
        "customer_id": "CUST-005",
        "account_number": "019-883410-1",
        "account_name": "F&B Group Retail & Hospitality Operating (SGD)",
        "account_type": "OPERATING",
        "currency": "SGD",
        "current_balance": 2340900.00,
        "available_balance": 2310000.00,
        "sgd_equivalent_balance": 2340900.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "STANDARD_CORPORATE_MANDATE",
    },
    {
        "account_id": "ACC-005-02",
        "customer_id": "CUST-005",
        "account_number": "019-883410-9",
        "account_name": "USD Agri-Commodity Import LC & Documentary Credits",
        "account_type": "TRADE_FINANCE_FX",
        "currency": "USD",
        "current_balance": 4780300.00,
        "available_balance": 4500000.00,
        "sgd_equivalent_balance": 6453405.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "TRADE_FINANCE_MANDATE",
    },
    {
        "account_id": "ACC-005-03",
        "customer_id": "CUST-005",
        "account_number": "019-883415-2",
        "account_name": "JPY Specialty Food & Wagyu Import Clearing (JPY)",
        "account_type": "MULTI_CURRENCY",
        "currency": "JPY",
        "current_balance": 98500000.00,
        "available_balance": 98500000.00,
        "sgd_equivalent_balance": 896350.00,
        "is_included_in_mandate_change": True,
        "mandate_scope_tag": "TRADE_FINANCE_MANDATE",
    },
    {
        "account_id": "ACC-005-04",
        "customer_id": "CUST-005",
        "account_number": "019-883419-5",
        "account_name": "Supplier Guarantee & Franchise Escrow Account (SGD)",
        "account_type": "ESCROW_TRUST",
        "currency": "SGD",
        "current_balance": 1500000.00,
        "available_balance": 1500000.00,
        "sgd_equivalent_balance": 1500000.00,
        "is_included_in_mandate_change": False,
        "mandate_scope_tag": "FRANCHISE_ESCROW",
    },
]


SIGNATORIES_SEED: list[dict[str, Any]] = [
    # CUST-001 (6 signatories: 3 Group A, 2 Group B, 1 Group C)
    {
        "signatory_id": "SIG-001-01",
        "customer_id": "CUST-001",
        "full_name": "Sarah Lim",
        "role_title": "Managing Director & Co-Founder",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****123A",
        "nationality": "SG",
        "email": "sarah.lim@technova.sg",
        "mobile_masked": "+65 9***1123",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "ACRA_BIZFILE_AND_SPECIMEN_CARD", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-001-02",
        "customer_id": "CUST-001",
        "full_name": "David Tan",
        "role_title": "Executive Director & CTO",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****889D",
        "nationality": "SG",
        "email": "david.tan@technova.sg",
        "mobile_masked": "+65 9***4889",
        "auth_method": "DIGISIGN_MOBILE",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "ACRA_BIZFILE_AND_SPECIMEN_CARD", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-001-03",
        "customer_id": "CUST-001",
        "full_name": "Michael Chang",
        "role_title": "Chief Financial Officer (CFO)",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****772C",
        "nationality": "SG",
        "email": "michael.chang@technova.sg",
        "mobile_masked": "+65 8***7720",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "PENDING_ACTIVATION",
        "specimen_signature_status": "VERIFIED_OCR_EXTRACTED",
        "specimen_metadata": {
            "source": "NRIC_AND_BRC09_OCR_SCAN",
            "confidence": 0.98,
            "extracted_at": "2026-09-18T04:30:00Z",
        },
        "individual_max_limit_sgd": None,
        "status": "PENDING_ADDITION",
    },
    {
        "signatory_id": "SIG-001-04",
        "customer_id": "CUST-001",
        "full_name": "Rachel Koh",
        "role_title": "VP of Finance",
        "signing_group": "B",
        "id_type": "NRIC",
        "id_number_masked": "S****456B",
        "nationality": "SG",
        "email": "rachel.koh@technova.sg",
        "mobile_masked": "+65 9***3456",
        "auth_method": "DIGISIGN_MOBILE",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2025", "confidence": 0.99},
        "individual_max_limit_sgd": 150000.00,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-001-05",
        "customer_id": "CUST-001",
        "full_name": "Marcus Yeo",
        "role_title": "Head of Corporate Treasury",
        "signing_group": "B",
        "id_type": "NRIC",
        "id_number_masked": "S****310M",
        "nationality": "SG",
        "email": "marcus.yeo@technova.sg",
        "mobile_masked": "+65 9***2310",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2025", "confidence": 0.99},
        "individual_max_limit_sgd": 150000.00,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-001-06",
        "customer_id": "CUST-001",
        "full_name": "Kenneth Yap",
        "role_title": "Senior Accounting Manager (Maker)",
        "signing_group": "C",
        "id_type": "NRIC",
        "id_number_masked": "S****901K",
        "nationality": "SG",
        "email": "kenneth.yap@technova.sg",
        "mobile_masked": "+65 8***9012",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2024", "confidence": 0.98},
        "individual_max_limit_sgd": 25000.00,
        "status": "ACTIVE",
    },
    # CUST-002 (5 signatories: 2 Group A, 2 Group B, 1 Group C)
    {
        "signatory_id": "SIG-002-01",
        "customer_id": "CUST-002",
        "full_name": "Raymond Ong",
        "role_title": "Executive Chairman",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****201Z",
        "nationality": "SG",
        "email": "raymond.ong@meridianpacific.sg",
        "mobile_masked": "+65 9***0201",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "BOARD_MANDATE_1998", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-002-02",
        "customer_id": "CUST-002",
        "full_name": "Helen Ong-Teo",
        "role_title": "Managing Director",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****204H",
        "nationality": "SG",
        "email": "helen.teo@meridianpacific.sg",
        "mobile_masked": "+65 9***0204",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "BOARD_MANDATE_2018", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-002-03",
        "customer_id": "CUST-002",
        "full_name": "Suresh Nair",
        "role_title": "Financial Controller",
        "signing_group": "B",
        "id_type": "NRIC",
        "id_number_masked": "S****619J",
        "nationality": "SG",
        "email": "suresh.nair@meridianpacific.sg",
        "mobile_masked": "+65 9***6619",
        "auth_method": "DIGISIGN_MOBILE",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2023", "confidence": 0.99},
        "individual_max_limit_sgd": 250000.00,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-002-04",
        "customer_id": "CUST-002",
        "full_name": "Wendy Phua",
        "role_title": "General Manager, Fleet Operations",
        "signing_group": "B",
        "id_type": "NRIC",
        "id_number_masked": "S****512W",
        "nationality": "SG",
        "email": "wendy.phua@meridianpacific.sg",
        "mobile_masked": "+65 8***5512",
        "auth_method": "DIGISIGN_MOBILE",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2024", "confidence": 0.98},
        "individual_max_limit_sgd": 100000.00,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-002-05",
        "customer_id": "CUST-002",
        "full_name": "Jason Lim",
        "role_title": "Accounts Payable Supervisor",
        "signing_group": "C",
        "id_type": "NRIC",
        "id_number_masked": "S****731L",
        "nationality": "SG",
        "email": "jason.lim@meridianpacific.sg",
        "mobile_masked": "+65 8***7731",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2024", "confidence": 0.97},
        "individual_max_limit_sgd": 50000.00,
        "status": "ACTIVE",
    },
    # CUST-003 (4 signatories: 2 Group A, 1 Group B, 1 Group C)
    {
        "signatory_id": "SIG-003-01",
        "customer_id": "CUST-003",
        "full_name": "Hendrik van der Berg",
        "role_title": "VP Regional Treasury APAC",
        "signing_group": "A",
        "id_type": "PASSPORT",
        "id_number_masked": "N****441P",
        "nationality": "NL",
        "email": "h.vanderberg@apexglobal.com",
        "mobile_masked": "+65 9***8441",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "GLOBAL_TREASURY_POA_2024", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-003-02",
        "customer_id": "CUST-003",
        "full_name": "Chuan Kai Wong",
        "role_title": "Singapore Resident Managing Director",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****118C",
        "nationality": "SG",
        "email": "ck.wong@apexglobal.com",
        "mobile_masked": "+65 9***9118",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "ACRA_DIRECTOR_REGISTRY", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-003-03",
        "customer_id": "CUST-003",
        "full_name": "Priya Ramanathan",
        "role_title": "Regional Cash & FX Director",
        "signing_group": "B",
        "id_type": "NRIC",
        "id_number_masked": "S****845R",
        "nationality": "SG",
        "email": "priya.r@apexglobal.com",
        "mobile_masked": "+65 9***3845",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2025", "confidence": 0.99},
        "individual_max_limit_sgd": 2000000.00,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-003-04",
        "customer_id": "CUST-003",
        "full_name": "Mei Ling Chow",
        "role_title": "Senior Treasury Settlements Analyst",
        "signing_group": "C",
        "id_type": "NRIC",
        "id_number_masked": "S****402M",
        "nationality": "SG",
        "email": "meiling.chow@apexglobal.com",
        "mobile_masked": "+65 8***4402",
        "auth_method": "DIGISIGN_MOBILE",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2025", "confidence": 0.98},
        "individual_max_limit_sgd": 250000.00,
        "status": "ACTIVE",
    },
    # CUST-004 (4 signatories: 1 Group A [Sole Managing Partner], 2 Group B, 1 Group C)
    {
        "signatory_id": "SIG-004-01",
        "customer_id": "CUST-004",
        "full_name": "Evelyn Tan",
        "role_title": "Senior Managing Partner",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****008A",
        "nationality": "SG",
        "email": "evelyn.tan@veritaslegal.sg",
        "mobile_masked": "+65 9***1008",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "LAW_SOCIETY_PANEL_2025", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-004-02",
        "customer_id": "CUST-004",
        "full_name": "Beatrice Chee",
        "role_title": "Managing Partner & Conveyancing Head",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****334B",
        "nationality": "SG",
        "email": "beatrice.chee@veritaslegal.sg",
        "mobile_masked": "+65 9***2334",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "LAW_SOCIETY_PANEL_2025", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-004-03",
        "customer_id": "CUST-004",
        "full_name": "Clara Seow",
        "role_title": "Partner, Corporate Finance",
        "signing_group": "B",
        "id_type": "NRIC",
        "id_number_masked": "S****551C",
        "nationality": "SG",
        "email": "clara.seow@veritaslegal.sg",
        "mobile_masked": "+65 9***4551",
        "auth_method": "DIGISIGN_MOBILE",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "LLP_DEED_SUPPLEMENT_2024", "confidence": 0.99},
        "individual_max_limit_sgd": 75000.00,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-004-04",
        "customer_id": "CUST-004",
        "full_name": "Siti Nurhaliza",
        "role_title": "Chief Legal Cashier",
        "signing_group": "C",
        "id_type": "NRIC",
        "id_number_masked": "S****812S",
        "nationality": "SG",
        "email": "siti.n@veritaslegal.sg",
        "mobile_masked": "+65 8***8812",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2023", "confidence": 0.98},
        "individual_max_limit_sgd": 75000.00,
        "status": "ACTIVE",
    },
    # CUST-005 (4 signatories: 2 Group A, 1 Group B, 1 Group C)
    {
        "signatory_id": "SIG-005-01",
        "customer_id": "CUST-005",
        "full_name": "Budi Santoso",
        "role_title": "Executive Chairman",
        "signing_group": "A",
        "id_type": "PASSPORT",
        "id_number_masked": "F****102B",
        "nationality": "ID",
        "email": "budi.santoso@banyanartisans.sg",
        "mobile_masked": "+65 9***7102",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "ACRA_DIRECTOR_FILING", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-005-02",
        "customer_id": "CUST-005",
        "full_name": "Victor Lim",
        "role_title": "Chief Executive Officer",
        "signing_group": "A",
        "id_type": "NRIC",
        "id_number_masked": "S****920V",
        "nationality": "SG",
        "email": "victor.lim@banyanartisans.sg",
        "mobile_masked": "+65 9***6920",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "ACRA_DIRECTOR_FILING", "confidence": 0.99},
        "individual_max_limit_sgd": None,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-005-03",
        "customer_id": "CUST-005",
        "full_name": "Farhan Ahmad",
        "role_title": "Head of Commodity Trade Finance",
        "signing_group": "B",
        "id_type": "NRIC",
        "id_number_masked": "S****673F",
        "nationality": "SG",
        "email": "farhan.ahmad@banyanartisans.sg",
        "mobile_masked": "+65 9***5673",
        "auth_method": "DIGISIGN_MOBILE",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2025", "confidence": 0.99},
        "individual_max_limit_sgd": 1000000.00,
        "status": "ACTIVE",
    },
    {
        "signatory_id": "SIG-005-04",
        "customer_id": "CUST-005",
        "full_name": "Boon Huat Yeo",
        "role_title": "Import/Export Documentary Credits Lead",
        "signing_group": "C",
        "id_type": "NRIC",
        "id_number_masked": "S****509Y",
        "nationality": "SG",
        "email": "boonhuat.yeo@banyanartisans.sg",
        "mobile_masked": "+65 8***3509",
        "auth_method": "IDEAL_DIGITAL_TOKEN",
        "ideal_status": "TOKEN_ACTIVE",
        "specimen_signature_status": "VERIFIED_ON_FILE",
        "specimen_metadata": {"source": "SPECIMEN_CARD_2024", "confidence": 0.98},
        "individual_max_limit_sgd": 150000.00,
        "status": "ACTIVE",
    },
]


SIGNING_RULES_SEED: list[dict[str, Any]] = [
    # CUST-001 (2 tiers)
    {
        "rule_id": "RULE-001-T1",
        "customer_id": "CUST-001",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 1,
        "tier_label": "Tier 1 — Standard Operational Payments",
        "min_amount_sgd": 0.00,
        "max_amount_sgd": 100000.00,
        "currency": "SGD",
        "rule_expression": "1A OR 2B",
        "human_readable_rule": "Any 1 Group A Signatory OR Any 2 Group B Signatories",
        "required_combinations": [{"A": 1}, {"B": 2}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-001-T2",
        "customer_id": "CUST-001",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 2,
        "tier_label": "Tier 2 — High-Value Treasury & Capital Transfers",
        "min_amount_sgd": 100000.01,
        "max_amount_sgd": None,
        "currency": "SGD",
        "rule_expression": "2A",
        "human_readable_rule": "Any 2 Group A Signatories Jointly",
        "required_combinations": [{"A": 2}],
        "requires_board_resolution_above": True,
    },
    # CUST-002 (3 tiers)
    {
        "rule_id": "RULE-002-T1",
        "customer_id": "CUST-002",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 1,
        "tier_label": "Tier 1 — Daily Port & Vendor Disbursements",
        "min_amount_sgd": 0.00,
        "max_amount_sgd": 50000.00,
        "currency": "SGD",
        "rule_expression": "1A OR 1B",
        "human_readable_rule": "Any 1 Group A Signatory OR Any 1 Group B Signatory",
        "required_combinations": [{"A": 1}, {"B": 1}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-002-T2",
        "customer_id": "CUST-002",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 2,
        "tier_label": "Tier 2 — Mid-Value Fleet & Freight Settlement",
        "min_amount_sgd": 50000.01,
        "max_amount_sgd": 250000.00,
        "currency": "SGD",
        "rule_expression": "1A + 1B",
        "human_readable_rule": "1 Group A Signatory AND 1 Group B Signatory Jointly",
        "required_combinations": [{"A": 1, "B": 1}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-002-T3",
        "customer_id": "CUST-002",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 3,
        "tier_label": "Tier 3 — Major Vessel CapEx & Trade LC Issuance",
        "min_amount_sgd": 250000.01,
        "max_amount_sgd": None,
        "currency": "SGD",
        "rule_expression": "2A",
        "human_readable_rule": "Both Group A Executive Directors Jointly",
        "required_combinations": [{"A": 2}],
        "requires_board_resolution_above": True,
    },
    # CUST-003 (3 tiers)
    {
        "rule_id": "RULE-003-T1",
        "customer_id": "CUST-003",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 1,
        "tier_label": "Tier 1 — Regional Working Capital Sweep",
        "min_amount_sgd": 0.00,
        "max_amount_sgd": 250000.00,
        "currency": "SGD",
        "rule_expression": "1A OR (1B + 1C)",
        "human_readable_rule": "Any 1 Group A Signatory OR (1 Group B + 1 Group C)",
        "required_combinations": [{"A": 1}, {"B": 1, "C": 1}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-003-T2",
        "customer_id": "CUST-003",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 2,
        "tier_label": "Tier 2 — Intercompany Liquidity & FX Settlement",
        "min_amount_sgd": 250000.01,
        "max_amount_sgd": 2000000.00,
        "currency": "SGD",
        "rule_expression": "1A + 1B",
        "human_readable_rule": "1 Group A Regional Director AND 1 Group B Cash Director",
        "required_combinations": [{"A": 1, "B": 1}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-003-T3",
        "customer_id": "CUST-003",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 3,
        "tier_label": "Tier 3 — Strategic Cross-Border Treasury Repatriation",
        "min_amount_sgd": 2000000.01,
        "max_amount_sgd": None,
        "currency": "SGD",
        "rule_expression": "2A",
        "human_readable_rule": "2 Group A Regional Managing Directors Jointly",
        "required_combinations": [{"A": 2}],
        "requires_board_resolution_above": True,
    },
    # CUST-004 (2 tiers)
    {
        "rule_id": "RULE-004-T1",
        "customer_id": "CUST-004",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 1,
        "tier_label": "Tier 1 — Chambers Office Operating Disbursements",
        "min_amount_sgd": 0.00,
        "max_amount_sgd": 75000.00,
        "currency": "SGD",
        "rule_expression": "1A OR (1B + 1C)",
        "human_readable_rule": "Any 1 Senior Equity Partner (Group A) OR (1 Partner Group B + Legal Cashier Group C)",
        "required_combinations": [{"A": 1}, {"B": 1, "C": 1}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-004-T2",
        "customer_id": "CUST-004",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 2,
        "tier_label": "Tier 2 — Statutory Conveyancing Client Escrow & High-Value Settlements",
        "min_amount_sgd": 75000.01,
        "max_amount_sgd": None,
        "currency": "SGD",
        "rule_expression": "2A",
        "human_readable_rule": "2 Equity Partners (Group A) Jointly per Law Society Conveyancing Rules",
        "required_combinations": [{"A": 2}],
        "requires_board_resolution_above": True,
    },
    # CUST-005 (3 tiers)
    {
        "rule_id": "RULE-005-T1",
        "customer_id": "CUST-005",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 1,
        "tier_label": "Tier 1 — F&B Outlet & Local Supplier Payments",
        "min_amount_sgd": 0.00,
        "max_amount_sgd": 150000.00,
        "currency": "SGD",
        "rule_expression": "1A OR (1B + 1C)",
        "human_readable_rule": "Any 1 Group A Executive OR (1 Group B Trade Head + 1 Group C Specialist)",
        "required_combinations": [{"A": 1}, {"B": 1, "C": 1}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-005-T2",
        "customer_id": "CUST-005",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 2,
        "tier_label": "Tier 2 — Regional Agri-Food Import Documentary Credits",
        "min_amount_sgd": 150000.01,
        "max_amount_sgd": 1000000.00,
        "currency": "SGD",
        "rule_expression": "1A + 1B",
        "human_readable_rule": "1 Group A Executive Director AND 1 Group B Head of Trade Finance",
        "required_combinations": [{"A": 1, "B": 1}],
        "requires_board_resolution_above": False,
    },
    {
        "rule_id": "RULE-005-T3",
        "customer_id": "CUST-005",
        "account_scope": "ALL_SELECTED_ACCOUNTS",
        "tier_order": 3,
        "tier_label": "Tier 3 — Bulk Commodity Charter & Hedging Settlements",
        "min_amount_sgd": 1000000.01,
        "max_amount_sgd": None,
        "currency": "SGD",
        "rule_expression": "2A + 1B",
        "human_readable_rule": "2 Group A Executive Directors AND 1 Group B Trade Finance Head",
        "required_combinations": [{"A": 2, "B": 1}],
        "requires_board_resolution_above": True,
    },
]


RESOLUTIONS_SEED: list[dict[str, Any]] = [
    {
        "resolution_id": "RES-001",
        "customer_id": "CUST-001",
        "resolution_ref": "DBS-BRC-09-2026-0918",
        "format_type": "STANDARD_BRC_09",
        "document_title": "Certified Extract of Directors' Resolution in Writing (Section 184A) — Mandate Amendment BRC-09",
        "meeting_date": "2026-09-15",
        "quorum_confirmed": True,
        "clause_checklist": {
            "quorum_verified": True,
            "target_accounts_referenced": True,
            "signing_matrix_aligned": True,
            "ideal_digisign_clause_included": True,
            "specimen_signature_ratification": True,
        },
        "extracted_text_summary": (
            "IT WAS RESOLVED THAT the banking mandate for accounts 001-928341-0 (SGD) and 001-928341-8 (USD) "
            "with DBS Bank Ltd be amended to appoint Chief Financial Officer Michael Chang (NRIC S****772C) "
            "as an Authorized Group A Signatory with full IDEAL Digital Token and DigiSign execution authority."
        ),
        "audit_score": 98,
        "audit_status": "COMPLIANT",
        "audit_findings": [
            {
                "clause": "Standard BRC-09 Electronic Banking Clause",
                "status": "PASS",
                "detail": "Explicitly authorizes DBS IDEAL Digital Token & Mobile DigiSign execution.",
            }
        ],
    },
    {
        "resolution_id": "RES-002",
        "customer_id": "CUST-002",
        "resolution_ref": "MPL-MIN-2026-0812",
        "format_type": "CUSTOM_BOARD_MINUTES",
        "document_title": "Minutes of Board of Directors Meeting — Maritime Fleet & EUR LC Mandate Update",
        "meeting_date": "2026-08-28",
        "quorum_confirmed": True,
        "clause_checklist": {
            "quorum_verified": True,
            "target_accounts_referenced": True,
            "signing_matrix_aligned": True,
            "ideal_digisign_clause_included": False,
            "specimen_signature_ratification": True,
        },
        "extracted_text_summary": (
            "Board minutes authorizing signing thresholds across 003-441092-1 (SGD), 003-441092-9 (USD), "
            "and 003-441095-4 (EUR). Note: Custom minutes omit standard DBS Clause 4(b) for electronic "
            "banking / IDEAL Mobile DigiSign authorization on the EUR LC account."
        ),
        "audit_score": 82,
        "audit_status": "ACTION_REQUIRED_CLAUSE_GAP",
        "audit_findings": [
            {
                "clause": "IDEAL Electronic Banking & DigiSign Clause 4(b)",
                "status": "ACTION_REQUIRED",
                "detail": "Custom Board Minutes must include explicit IDEAL electronic banking ratification or adopt Standard BRC-09.",
            }
        ],
    },
    {
        "resolution_id": "RES-003",
        "customer_id": "CUST-003",
        "resolution_ref": "AGH-BRC-09-2026-0905",
        "format_type": "STANDARD_BRC_09",
        "document_title": "APAC Regional Treasury Board Resolution — Standard BRC-09 Mandate Schedule",
        "meeting_date": "2026-09-05",
        "quorum_confirmed": True,
        "clause_checklist": {
            "quorum_verified": True,
            "target_accounts_referenced": True,
            "signing_matrix_aligned": True,
            "ideal_digisign_clause_included": True,
            "specimen_signature_ratification": True,
        },
        "extracted_text_summary": (
            "Full BRC-09 resolution covering APAC Cash Pool accounts 008-772301-0 (SGD), 008-772301-8 (USD), "
            "and 008-772308-5 (CNH) with Host-to-Host and IDEAL Token authorization."
        ),
        "audit_score": 100,
        "audit_status": "COMPLIANT",
        "audit_findings": [],
    },
    {
        "resolution_id": "RES-004",
        "customer_id": "CUST-004",
        "resolution_ref": "VLA-LLP-RES-2026-04",
        "format_type": "LLP_PARTNERS_RESOLUTION",
        "document_title": "All-Partners Resolution Pursuant to LLP Agreement Clause 19 & Law Society Rules",
        "meeting_date": "2026-09-10",
        "quorum_confirmed": True,
        "clause_checklist": {
            "quorum_verified": True,
            "target_accounts_referenced": True,
            "signing_matrix_aligned": True,
            "ideal_digisign_clause_included": True,
            "specimen_signature_ratification": True,
        },
        "extracted_text_summary": (
            "Unanimous resolution of Equity Partners confirming dual Group A Equity Partner signing rules "
            "for Statutory Client Trust Escrow Account 012-559109-0 and Chambers Operating Account 012-559102-3."
        ),
        "audit_score": 96,
        "audit_status": "COMPLIANT",
        "audit_findings": [],
    },
    {
        "resolution_id": "RES-005",
        "customer_id": "CUST-005",
        "resolution_ref": "BAF-BRC-09-2026-0915",
        "format_type": "STANDARD_BRC_09",
        "document_title": "Directors' Resolution in Writing — Commodity Trade Finance & Hospitality Mandate",
        "meeting_date": "2026-09-12",
        "quorum_confirmed": True,
        "clause_checklist": {
            "quorum_verified": True,
            "target_accounts_referenced": True,
            "signing_matrix_aligned": True,
            "ideal_digisign_clause_included": True,
            "specimen_signature_ratification": True,
        },
        "extracted_text_summary": (
            "Standard BRC-09 resolution ratifying Group A and Group B joint trade finance signing matrix "
            "for SGD, USD, and JPY accounts."
        ),
        "audit_score": 97,
        "audit_status": "COMPLIANT",
        "audit_findings": [],
    },
]


APPLICATIONS_SEED: list[dict[str, Any]] = [
    {
        "application_id": "APP-001",
        "customer_id": "CUST-001",
        "resolution_id": "RES-001",
        "application_ref": "COM-2026-88412",
        "current_stage": 2,
        "status": "PARTIALLY_SIGNED",
        "summary_description": "Appointment of CFO Michael Chang to Group A & review of Tier 1 operational threshold.",
        "affected_account_ids": ["ACC-001-01", "ACC-001-02"],
        "mandate_diff_snapshot": {
            "has_changes": True,
            "accounts_included_count": 2,
            "signatories_added": [
                {
                    "signatory_id": "SIG-001-03",
                    "full_name": "Michael Chang",
                    "role_title": "Chief Financial Officer (CFO)",
                    "signing_group": "A",
                }
            ],
            "signatories_revoked": [],
            "rules_modified": False,
        },
        "digisign_signers": [
            {
                "signer_id": "SIG-001-01",
                "full_name": "Sarah Lim",
                "role_title": "Managing Director & Co-Founder",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "SIGNED_VIA_IDEAL_TOKEN",
                "signed_at": "2026-09-18T04:20:00Z",
            },
            {
                "signer_id": "SIG-001-02",
                "full_name": "David Tan",
                "role_title": "Executive Director & CTO",
                "signing_group": "A",
                "auth_method": "DIGISIGN_MOBILE",
                "status": "PENDING_DIGISIGN_SMS",
                "signed_at": None,
            },
        ],
        "submitted_by": "Sarah Lim (Managing Director)",
    },
    {
        "application_id": "APP-002",
        "customer_id": "CUST-002",
        "resolution_id": "RES-002",
        "application_ref": "COM-2026-79104",
        "current_stage": 4,
        "status": "IN_REVIEW_DRAFT",
        "summary_description": "Update EUR Cold-Chain Equipment LC account signing mandate & align custom board minutes.",
        "affected_account_ids": ["ACC-002-01", "ACC-002-02", "ACC-002-03"],
        "mandate_diff_snapshot": {
            "has_changes": True,
            "accounts_included_count": 3,
            "signatories_added": [],
            "signatories_revoked": [],
            "rules_modified": True,
        },
        "digisign_signers": [
            {
                "signer_id": "SIG-002-01",
                "full_name": "Raymond Ong",
                "role_title": "Executive Chairman",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "SIGNED_VIA_IDEAL_TOKEN",
                "signed_at": "2026-09-17T11:15:00Z",
            },
            {
                "signer_id": "SIG-002-02",
                "full_name": "Helen Ong-Teo",
                "role_title": "Managing Director",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "PENDING_DIGISIGN_SMS",
                "signed_at": None,
            },
        ],
        "submitted_by": "Raymond Ong (Executive Chairman)",
    },
    {
        "application_id": "APP-003",
        "customer_id": "CUST-003",
        "resolution_id": "RES-003",
        "application_ref": "COM-2026-65019",
        "current_stage": 5,
        "status": "APPROVED_AND_EFFECTIVE",
        "summary_description": "APAC Treasury Center Multi-Currency Sweep Mandate Ratification.",
        "affected_account_ids": ["ACC-003-01", "ACC-003-02", "ACC-003-03"],
        "mandate_diff_snapshot": {"has_changes": False, "accounts_included_count": 3},
        "digisign_signers": [
            {
                "signer_id": "SIG-003-01",
                "full_name": "Hendrik van der Berg",
                "role_title": "VP Regional Treasury APAC",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "SIGNED_VIA_IDEAL_TOKEN",
                "signed_at": "2026-09-06T09:10:00Z",
            },
            {
                "signer_id": "SIG-003-02",
                "full_name": "Chuan Kai Wong",
                "role_title": "Singapore Resident Managing Director",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "SIGNED_VIA_DIGISIGN",
                "signed_at": "2026-09-06T10:04:00Z",
            },
        ],
        "submitted_by": "Hendrik van der Berg (VP Regional Treasury APAC)",
    },
    {
        "application_id": "APP-004",
        "customer_id": "CUST-004",
        "resolution_id": "RES-004",
        "application_ref": "COM-2026-54128",
        "current_stage": 3,
        "status": "PENDING_BOARD_SIGNATURES",
        "summary_description": "Law Society Conveyancing Escrow Dual-Partner Mandate Confirmation.",
        "affected_account_ids": ["ACC-004-01", "ACC-004-02", "ACC-004-03"],
        "mandate_diff_snapshot": {"has_changes": True, "accounts_included_count": 3},
        "digisign_signers": [
            {
                "signer_id": "SIG-004-01",
                "full_name": "Arjun Menon SC",
                "role_title": "Senior Equity Partner",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "SIGNED_VIA_IDEAL_TOKEN",
                "signed_at": "2026-09-14T16:30:00Z",
            },
            {
                "signer_id": "SIG-004-02",
                "full_name": "Beatrice Chee",
                "role_title": "Managing Partner & Conveyancing Head",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "PENDING_DIGISIGN_SMS",
                "signed_at": None,
            },
        ],
        "submitted_by": "Arjun Menon SC (Senior Equity Partner)",
    },
    {
        "application_id": "APP-005",
        "customer_id": "CUST-005",
        "resolution_id": "RES-005",
        "application_ref": "COM-2026-43901",
        "current_stage": 2,
        "status": "PARTIALLY_SIGNED",
        "summary_description": "Agri-Food & JPY Import Clearing Documentary Credit Mandate Update.",
        "affected_account_ids": ["ACC-005-01", "ACC-005-02", "ACC-005-03"],
        "mandate_diff_snapshot": {"has_changes": True, "accounts_included_count": 3},
        "digisign_signers": [
            {
                "signer_id": "SIG-005-01",
                "full_name": "Budi Santoso",
                "role_title": "Executive Chairman",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "SIGNED_VIA_IDEAL_TOKEN",
                "signed_at": "2026-09-16T08:45:00Z",
            },
            {
                "signer_id": "SIG-005-02",
                "full_name": "Victor Lim",
                "role_title": "Chief Executive Officer",
                "signing_group": "A",
                "auth_method": "IDEAL_DIGITAL_TOKEN",
                "status": "PENDING_DIGISIGN_SMS",
                "signed_at": None,
            },
        ],
        "submitted_by": "Victor Lim (Chief Executive Officer)",
    },
]


AUDIT_LOGS_SEED: list[dict[str, Any]] = [
    {
        "customer_id": "CUST-001",
        "application_id": "APP-001",
        "event_type": "MANDATE_WORKSPACE_INITIALIZED",
        "actor_name": "Sarah Lim (Managing Director)",
        "actor_channel": "DBS_IDEAL_CORP_PORTAL",
        "target_entity": "CUST-001",
        "before_state": {"active_mandate_version": 3},
        "after_state": {"selected_accounts": ["001-928341-0", "001-928341-8"]},
        "compliance_notes": "Authenticated via DBS IDEAL Hardware/Mobile Token (Corp ID: IDEALSG-TN2018).",
    },
    {
        "customer_id": "CUST-001",
        "application_id": "APP-001",
        "event_type": "OCR_DOCUMENT_EXTRACTED",
        "actor_name": "Gemini Live 3.8 Compliance Copilot",
        "actor_channel": "GEMINI_LIVE_MULTIMODAL",
        "target_entity": "SIG-001-03 (Michael Chang)",
        "before_state": None,
        "after_state": {"full_name": "Michael Chang", "nric": "S****772C", "group": "A", "role": "CFO"},
        "compliance_notes": "Extracted NRIC & specimen signature from certified BRC-09 Schedule (98.4% OCR confidence).",
    },
    {
        "customer_id": "CUST-001",
        "application_id": "APP-001",
        "event_type": "BOARD_RESOLUTION_PREFLIGHT_PASS",
        "actor_name": "Gemini Live 3.8 Compliance Copilot",
        "actor_channel": "GEMINI_LIVE_MULTIMODAL",
        "target_entity": "DBS-BRC-09-2026-0918",
        "before_state": {"audit_status": "PENDING_AUDIT"},
        "after_state": {"audit_status": "COMPLIANT", "audit_score": 98},
        "compliance_notes": "All 5 BRC-09 governance & electronic banking clauses verified.",
    },
    {
        "customer_id": "CUST-001",
        "application_id": "APP-001",
        "event_type": "MAKER_IDEAL_TOKEN_SIGNED",
        "actor_name": "Sarah Lim (Managing Director)",
        "actor_channel": "IDEAL_DIGITAL_TOKEN",
        "target_entity": "COM-2026-88412",
        "before_state": {"status": "IN_REVIEW_DRAFT"},
        "after_state": {"status": "PARTIALLY_SIGNED", "awaiting_cosigner": "David Tan"},
        "compliance_notes": "Primary Group A Director cryptographic signature recorded; SMS DigiSign link dispatched to David Tan.",
    },
    {
        "customer_id": "CUST-002",
        "application_id": "APP-002",
        "event_type": "MANDATE_WORKSPACE_INITIALIZED",
        "actor_name": "Raymond Ong (Executive Chairman)",
        "actor_channel": "DBS_IDEAL_CORP_PORTAL",
        "target_entity": "CUST-002",
        "before_state": {"active_mandate_version": 2},
        "after_state": {"selected_accounts": ["003-441092-1", "003-441092-9", "003-441095-4"]},
        "compliance_notes": "Initiated mandate review for SGD, USD, and EUR Cold-Chain LC accounts.",
    },
    {
        "customer_id": "CUST-002",
        "application_id": "APP-002",
        "event_type": "BOARD_RESOLUTION_CLAUSE_WARNING",
        "actor_name": "Gemini Live 3.8 Compliance Copilot",
        "actor_channel": "GEMINI_LIVE_MULTIMODAL",
        "target_entity": "MPL-MIN-2026-0812",
        "before_state": {"audit_status": "PENDING_AUDIT"},
        "after_state": {"audit_status": "ACTION_REQUIRED_CLAUSE_GAP", "audit_score": 82},
        "compliance_notes": "Detected missing Clause 4(b) IDEAL electronic banking authorization in custom board minutes.",
    },
    {
        "customer_id": "CUST-002",
        "application_id": "APP-002",
        "event_type": "TRANSACTION_SIMULATION_EXECUTED",
        "actor_name": "Suresh Nair (Financial Controller)",
        "actor_channel": "GEMINI_LIVE_VOICE",
        "target_entity": "RULE-002-T2",
        "before_state": None,
        "after_state": {"simulated_amount_sgd": 180000.0, "matched_rule": "1A + 1B"},
        "compliance_notes": "Verified joint Group A + Group B signing combinations for EUR 120,000 LC settlement.",
    },
    {
        "customer_id": "CUST-003",
        "application_id": "APP-003",
        "event_type": "HOST_TO_HOST_MANDATE_SYNC",
        "actor_name": "Hendrik van der Berg (VP Treasury APAC)",
        "actor_channel": "IDEAL_HOST_TO_HOST",
        "target_entity": "CUST-003",
        "before_state": {"active_mandate_version": 4},
        "after_state": {"active_mandate_version": 5, "status": "APPROVED_AND_EFFECTIVE"},
        "compliance_notes": "APAC Cash Concentration Sweep mandate synchronized with SAP Treasury ERP.",
    },
    {
        "customer_id": "CUST-003",
        "application_id": "APP-003",
        "event_type": "BOARD_RESOLUTION_PREFLIGHT_PASS",
        "actor_name": "Gemini Live 3.8 Compliance Copilot",
        "actor_channel": "GEMINI_LIVE_MULTIMODAL",
        "target_entity": "AGH-BRC-09-2026-0905",
        "before_state": {"audit_score": 0},
        "after_state": {"audit_score": 100, "audit_status": "COMPLIANT"},
        "compliance_notes": "Standard BRC-09 schedule verified with 100/100 compliance score.",
    },
    {
        "customer_id": "CUST-003",
        "application_id": "APP-003",
        "event_type": "DIGISIGN_DUAL_EXECUTION_COMPLETE",
        "actor_name": "Chuan Kai Wong (Resident MD)",
        "actor_channel": "IDEAL_DIGITAL_TOKEN",
        "target_entity": "COM-2026-65019",
        "before_state": {"status": "PARTIALLY_SIGNED"},
        "after_state": {"status": "APPROVED_AND_EFFECTIVE"},
        "compliance_notes": "Both Group A Directors completed hardware token signing; core banking updated.",
    },
    {
        "customer_id": "CUST-004",
        "application_id": "APP-004",
        "event_type": "LAW_SOCIETY_ESCROW_POLICY_CHECK",
        "actor_name": "Arjun Menon SC (Senior Equity Partner)",
        "actor_channel": "DBS_IDEAL_CORP_PORTAL",
        "target_entity": "ACC-004-02 (Client Trust Escrow)",
        "before_state": None,
        "after_state": {"rule_expression": "2A", "dual_partner_enforced": True},
        "compliance_notes": "Enforced mandatory 2 Equity Partner (Group A) co-signing on Conveyancing Client Trust account.",
    },
    {
        "customer_id": "CUST-004",
        "application_id": "APP-004",
        "event_type": "LLP_RESOLUTION_AUDITED",
        "actor_name": "Gemini Live 3.8 Compliance Copilot",
        "actor_channel": "GEMINI_LIVE_MULTIMODAL",
        "target_entity": "VLA-LLP-RES-2026-04",
        "before_state": None,
        "after_state": {"audit_score": 96, "audit_status": "COMPLIANT"},
        "compliance_notes": "Verified unanimous Equity Partner endorsement under LLP Act Cap. 163A.",
    },
    {
        "customer_id": "CUST-004",
        "application_id": "APP-004",
        "event_type": "MAKER_IDEAL_TOKEN_SIGNED",
        "actor_name": "Arjun Menon SC",
        "actor_channel": "IDEAL_DIGITAL_TOKEN",
        "target_entity": "COM-2026-54128",
        "before_state": {"status": "IN_REVIEW_DRAFT"},
        "after_state": {"status": "PENDING_BOARD_SIGNATURES"},
        "compliance_notes": "Senior Equity Partner signed; awaiting Managing Partner Beatrice Chee co-signature.",
    },
    {
        "customer_id": "CUST-005",
        "application_id": "APP-005",
        "event_type": "TRADE_FINANCE_MANDATE_REVIEW",
        "actor_name": "Victor Lim (CEO)",
        "actor_channel": "DBS_IDEAL_CORP_PORTAL",
        "target_entity": "CUST-005",
        "before_state": {"active_mandate_version": 2},
        "after_state": {"currencies_enabled": ["SGD", "USD", "JPY"]},
        "compliance_notes": "Configured Tier 1-3 trade finance and documentary credit signing rules.",
    },
    {
        "customer_id": "CUST-005",
        "application_id": "APP-005",
        "event_type": "BOARD_RESOLUTION_PREFLIGHT_PASS",
        "actor_name": "Gemini Live 3.8 Compliance Copilot",
        "actor_channel": "GEMINI_LIVE_MULTIMODAL",
        "target_entity": "BAF-BRC-09-2026-0915",
        "before_state": None,
        "after_state": {"audit_score": 97, "audit_status": "COMPLIANT"},
        "compliance_notes": "Verified BRC-09 documentary credit and FX hedging mandate clauses.",
    },
    {
        "customer_id": "CUST-005",
        "application_id": "APP-005",
        "event_type": "MAKER_IDEAL_TOKEN_SIGNED",
        "actor_name": "Budi Santoso (Executive Chairman)",
        "actor_channel": "IDEAL_DIGITAL_TOKEN",
        "target_entity": "COM-2026-43901",
        "before_state": {"status": "IN_REVIEW_DRAFT"},
        "after_state": {"status": "PARTIALLY_SIGNED"},
        "compliance_notes": "Executive Chairman signed via IDEAL Digital Token; awaiting CEO Victor Lim co-signature.",
    },
]


def _insert_customer_bundle(cur: Any, customer_id: str) -> None:
    """Insert or refresh seed records for a single customer_id."""
    cust = next(c for c in CUSTOMERS_SEED if c["customer_id"] == customer_id)
    cur.execute(
        """
        INSERT INTO corporate_customers (
            customer_id, company_name, uen, entity_type, industry,
            incorporation_country, kyc_status, ideal_corp_id, ideal_auth_status,
            active_mandate_version, mandate_status, relationship_manager,
            registered_address, governance_policy
        ) VALUES (
            %(customer_id)s, %(company_name)s, %(uen)s, %(entity_type)s, %(industry)s,
            %(incorporation_country)s, %(kyc_status)s, %(ideal_corp_id)s, %(ideal_auth_status)s,
            %(active_mandate_version)s, %(mandate_status)s, %(relationship_manager)s,
            %(registered_address)s, %(governance_policy)s
        )
        ON CONFLICT (customer_id) DO UPDATE SET
            company_name = EXCLUDED.company_name,
            uen = EXCLUDED.uen,
            entity_type = EXCLUDED.entity_type,
            industry = EXCLUDED.industry,
            kyc_status = EXCLUDED.kyc_status,
            ideal_corp_id = EXCLUDED.ideal_corp_id,
            ideal_auth_status = EXCLUDED.ideal_auth_status,
            active_mandate_version = EXCLUDED.active_mandate_version,
            mandate_status = EXCLUDED.mandate_status,
            relationship_manager = EXCLUDED.relationship_manager,
            registered_address = EXCLUDED.registered_address,
            governance_policy = EXCLUDED.governance_policy,
            updated_at = NOW();
        """,
        {**cust, "governance_policy": json.dumps(cust["governance_policy"])},
    )

    cur.execute("DELETE FROM mandate_audit_logs WHERE customer_id = %s;", (customer_id,))
    cur.execute("DELETE FROM mandate_change_applications WHERE customer_id = %s;", (customer_id,))
    cur.execute("DELETE FROM board_resolutions WHERE customer_id = %s;", (customer_id,))
    cur.execute("DELETE FROM signing_rules WHERE customer_id = %s;", (customer_id,))
    cur.execute("DELETE FROM signatories WHERE customer_id = %s;", (customer_id,))
    cur.execute("DELETE FROM bank_accounts WHERE customer_id = %s;", (customer_id,))

    for acc in [a for a in ACCOUNTS_SEED if a["customer_id"] == customer_id]:
        cur.execute(
            """
            INSERT INTO bank_accounts (
                account_id, customer_id, account_number, account_name, account_type,
                currency, current_balance, available_balance, sgd_equivalent_balance,
                is_included_in_mandate_change, mandate_scope_tag, status
            ) VALUES (
                %(account_id)s, %(customer_id)s, %(account_number)s, %(account_name)s, %(account_type)s,
                %(currency)s, %(current_balance)s, %(available_balance)s, %(sgd_equivalent_balance)s,
                %(is_included_in_mandate_change)s, %(mandate_scope_tag)s, 'ACTIVE'
            );
            """,
            acc,
        )

    for sig in [s for s in SIGNATORIES_SEED if s["customer_id"] == customer_id]:
        cur.execute(
            """
            INSERT INTO signatories (
                signatory_id, customer_id, full_name, role_title, signing_group,
                id_type, id_number_masked, nationality, email, mobile_masked,
                auth_method, ideal_status, specimen_signature_status, specimen_metadata,
                individual_max_limit_sgd, status
            ) VALUES (
                %(signatory_id)s, %(customer_id)s, %(full_name)s, %(role_title)s, %(signing_group)s,
                %(id_type)s, %(id_number_masked)s, %(nationality)s, %(email)s, %(mobile_masked)s,
                %(auth_method)s, %(ideal_status)s, %(specimen_signature_status)s, %(specimen_metadata)s,
                %(individual_max_limit_sgd)s, %(status)s
            );
            """,
            {**sig, "specimen_metadata": json.dumps(sig["specimen_metadata"])},
        )

    for rule in [r for r in SIGNING_RULES_SEED if r["customer_id"] == customer_id]:
        cur.execute(
            """
            INSERT INTO signing_rules (
                rule_id, customer_id, account_scope, tier_order, tier_label,
                min_amount_sgd, max_amount_sgd, currency, rule_expression,
                human_readable_rule, required_combinations, requires_board_resolution_above, is_active
            ) VALUES (
                %(rule_id)s, %(customer_id)s, %(account_scope)s, %(tier_order)s, %(tier_label)s,
                %(min_amount_sgd)s, %(max_amount_sgd)s, %(currency)s, %(rule_expression)s,
                %(human_readable_rule)s, %(required_combinations)s, %(requires_board_resolution_above)s, TRUE
            );
            """,
            {**rule, "required_combinations": json.dumps(rule["required_combinations"])},
        )

    for res in [r for r in RESOLUTIONS_SEED if r["customer_id"] == customer_id]:
        cur.execute(
            """
            INSERT INTO board_resolutions (
                resolution_id, customer_id, resolution_ref, format_type, document_title,
                meeting_date, quorum_confirmed, clause_checklist, extracted_text_summary,
                audit_score, audit_status, audit_findings
            ) VALUES (
                %(resolution_id)s, %(customer_id)s, %(resolution_ref)s, %(format_type)s, %(document_title)s,
                %(meeting_date)s, %(quorum_confirmed)s, %(clause_checklist)s, %(extracted_text_summary)s,
                %(audit_score)s, %(audit_status)s, %(audit_findings)s
            );
            """,
            {
                **res,
                "clause_checklist": json.dumps(res["clause_checklist"]),
                "audit_findings": json.dumps(res["audit_findings"]),
            },
        )

    for app in [a for a in APPLICATIONS_SEED if a["customer_id"] == customer_id]:
        cur.execute(
            """
            INSERT INTO mandate_change_applications (
                application_id, customer_id, resolution_id, application_ref,
                current_stage, status, summary_description, affected_account_ids,
                mandate_diff_snapshot, digisign_signers, submitted_by, submitted_at
            ) VALUES (
                %(application_id)s, %(customer_id)s, %(resolution_id)s, %(application_ref)s,
                %(current_stage)s, %(status)s, %(summary_description)s, %(affected_account_ids)s,
                %(mandate_diff_snapshot)s, %(digisign_signers)s, %(submitted_by)s, NOW()
            );
            """,
            {
                **app,
                "affected_account_ids": json.dumps(app["affected_account_ids"]),
                "mandate_diff_snapshot": json.dumps(app["mandate_diff_snapshot"]),
                "digisign_signers": json.dumps(app["digisign_signers"]),
            },
        )

    for log in [l for l in AUDIT_LOGS_SEED if l["customer_id"] == customer_id]:
        cur.execute(
            """
            INSERT INTO mandate_audit_logs (
                customer_id, application_id, event_type, actor_name, actor_channel,
                target_entity, before_state, after_state, compliance_notes
            ) VALUES (
                %(customer_id)s, %(application_id)s, %(event_type)s, %(actor_name)s, %(actor_channel)s,
                %(target_entity)s, %(before_state)s, %(after_state)s, %(compliance_notes)s
            );
            """,
            {
                **log,
                "before_state": json.dumps(log["before_state"]) if log["before_state"] else None,
                "after_state": json.dumps(log["after_state"]) if log["after_state"] else None,
            },
        )


def seed_single_customer(customer_id: str) -> dict[str, Any]:
    """Reset a single customer profile (`CUST-001`..`CUST-005`) to its canonical seed state."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            _insert_customer_bundle(cur, customer_id)
    return {"status": "success", "reset_customer_id": customer_id}


def seed_all_data(reset_existing: bool = True) -> dict[str, int]:
    """Populate all 5 corporate customer profiles and initialize `active_workspace_state`."""
    schema_file = PROJECT_ROOT / "schema" / "schema.sql"
    with get_connection() as conn:
        with conn.cursor() as cur:
            if schema_file.exists():
                cur.execute(schema_file.read_text(encoding="utf-8"))
            for cust in CUSTOMERS_SEED:
                _insert_customer_bundle(cur, cust["customer_id"])

            cur.execute(
                """
                INSERT INTO active_workspace_state (
                    workspace_id, active_customer_id, active_stage,
                    last_simulated_amount_sgd, last_simulated_currency, last_tool_executed
                ) VALUES ('DEFAULT_WORKSPACE', 'CUST-001', 1, 150000.00, 'SGD', 'seed_all_data')
                ON CONFLICT (workspace_id) DO UPDATE SET
                    active_customer_id = 'CUST-001',
                    active_stage = 1,
                    last_simulated_amount_sgd = 150000.00,
                    last_simulated_currency = 'SGD',
                    last_tool_executed = 'seed_all_data',
                    updated_at = NOW();
                """
            )

            counts = {}
            for tbl in [
                "corporate_customers",
                "bank_accounts",
                "signatories",
                "signing_rules",
                "board_resolutions",
                "mandate_change_applications",
                "mandate_audit_logs",
                "active_workspace_state",
            ]:
                cur.execute(f"SELECT COUNT(*) AS cnt FROM {tbl};")
                counts[tbl] = int(cur.fetchone()["cnt"])
    return counts


if __name__ == "__main__":
    summary = seed_all_data(reset_existing=True)
    print("[seed] Successfully populated PostgreSQL corporate_mandate_db:", json.dumps(summary, indent=2))
